---
dist: bionic
language: ruby
cache: bundler
before_install:
  - yes | gem update --system
  - bundle --version
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=centos7-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=centos7-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian9-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian9-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
    services: docker
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  webhooks: https://voxpupu.li/incoming/travis
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "d532jz5QRujx8orG3QPdhtU6bYOkEpSqj4AeC2h8cyDyyzi0JcbnTWUmhpx69jcS7WvAkj4fPYdYQbE/OxdgFegVaG5jmvG0rfFOPJsLKpgXKAHy3cCS2VFQcNXUHwFoDbTxW13aemR1Qy7Cw+WvnNzgoCoL1vTSGR/T81k5+tBfScQIzM7rs5fVctxNngWij7iEQSU2NQKCwhPB80G5ZdN4INb+K69sDKu4KkybulzrYEI6ZPX6FGEImkGf3ub8Qa3o3wy3l3bknxDfqi1WYdict8WZdr/et9hUIicLdLEypCCAzsc7fLKzVrfuXJMvivaFW2VMes1c/cVHBC5c+9eFP/vTREGa7HeWuvhLTTUUc5gzfUPYIbdAaulQs+cXaoWouTThZN7JEL1XZRZQ7vhbSylob+6UeKc27vmjL37kixY3iUN0hIumvpKQDB27tvJHcH6JAxZ8UWZ/VIeenqalLWFHyLe8GJnHkKHdCllW7cl0bVL9HR+1HY2RHJgCR7oWi/+CCn+0D48D1hx88gH9nXk6E9RXbTRlE4bZFs0Q0EGF1j6vNNwDtZO1cPeJnwM0LX3jSLL1uS1O2oeR+V66sFDCEccYtPZOPsIz3fcQPHv+Cfv7KlHrIn24YIPT6EI6VdhEAzuFfVMOWnAq0qAL5J8rjF6ssZK6QvTm/sA="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
